"""Creating functions to experiment with unit testing."""

__author__ = "730325952"


def only_evens(numbers: list[int]) -> list[int]:
    """Determines which numbers in the list are even."""
    tracer: list[int] = []
    for number in numbers:
        if number % 2 == 0:
            tracer.append(number)
    return tracer


def sub(numbers_two: list[int], x: int, y: int) -> list[int]:
    """A list that is a subset of the given list generated by index values."""
    second_tracer: list[int] = []
    while x <= y - 1 and len(numbers_two) > 0 and x < len(numbers_two) and y > 0:
        if x < 0:
            x = 0
        if y > len(numbers_two):
            y = len(numbers_two)
        second_tracer.append(numbers_two[x])
        x += 1
    return second_tracer


def concat(first_list: list[int], second_list: list[int]) -> list[int]:
    """Two lists combined into one list."""
    final_tracer: list[int] = []
    for first in first_list:
        final_tracer.append(first)
    for second in second_list:
        final_tracer.append(second)
    return final_tracer